In [2]:
inputs = [1, 2, 3, 2.5]
weights = [
  [0.2, 0.8, -0.5, 1],
  [0.5, -0.91, 0.26, -0.5],
  [-0.26, -0.27, 0.17, 0.87]
]
biases = [2, 3, 0.5]

# Output of current layer
layer_outputs = []

# For each neuron
for neuron_weights, neuron_bias in zip( weights, biases ):
  # Zeroed output of given neuron
  neuron_output = 0
  # For each input and weight to the neuron
  for n_input, weight in zip(inputs, neuron_weights):
    # Multiply this input by associated weight
    # and add to the neuron's output variable
    neuron_output += n_input * weight
  # Add bias
  neuron_output += neuron_bias
  # Put neuron's result to the layer's output list 
  layer_outputs.append( neuron_output )

print( layer_outputs )

[4.8, 1.21, 2.385]


In [9]:
import numpy as np

A = np.array([
  [1, 2, 3, 4],
  [5, 6, 7, 8],
  [9, 10, 11, 12]
])

B = np.array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9],
  [10, 11, 12]
])

# C = np.dot(A, B)
# C = np.multiply( A, B )
#C = np.matmul( A, B )
# C = A.dot( B )
C = A @ B

print( C )

[[ 70  80  90]
 [158 184 210]
 [246 288 330]]


In [10]:
inputs = [
  [1.0, 2.0, 3.0, 2.5],
  [2.0, 5.0, -1.0, 2.0],
  [-1.5, 2.7, 3.3, -0.8]
]

weights = [
  [0.2, 0.8, -0.5, 1.0],
  [0.5, -0.91, 0.26, -0.5],
  [-0.26, -0.27, 0.17, 0.87]
]

biases = [ 2.0, 3.0, 0.5 ]

layer_outputs = np.dot( inputs, np.array( weights ).T ) + biases

print( layer_outputs )

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [11]:
inputs = [
  [ 1, 2, 3, 2.5 ],
  [ 2., 5., -1., 2 ],
  [ -1.5, 2.7, 3.3, -0.8 ]
]

weights = [
  [ 0.2, 0.8, -0.5, 1 ],
  [ 0.5, -0.91, 0.26, -0.5 ],
  [ -0.26, -0.27, 0.17, 0.87 ]
]

biases = [ 2, 3, 0.5 ]

weights2 = [
  [ 0.1, -0.14, 0.5 ],
  [ -0.5, 0.12, -0.33 ],
  [ -0.44, 0.73, -0.13 ]
]

biases2 = [ -1, 2, -0.5 ]

layer1_outputs = np.dot( inputs, np.array( weights ).T ) + biases

layer2_outputs = np.dot( layer1_outputs, np.array( weights2 ).T ) + biases2

print( layer2_outputs )

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]
