In [1]:
# Categorical Cross-Entropy Loss

import math

# An example output from the output layer of the neural network
softmax_output = [0.7, 0.1, 0.2]

# Ground truth
target_output = [1, 0, 0]

loss = -(
    math.log(softmax_output[0]) * target_output[0] +
    math.log(softmax_output[1]) * target_output[1] +
    math.log(softmax_output[2]) * target_output[2]
)

print( loss )

0.35667494393873245


In [3]:
# Categorical Cross-Entropy Loss

loss = -math.log( softmax_output[0] )

print( loss )

0.35667494393873245


In [4]:
import math

print( math.log( 1. ) )
print( math.log( 0.95 ) )
print( math.log( 0.9 ) )
print( math.log( 0.8 ) )
print( math.log( 0.7 ) )
print( math.log( 0.6 ) )
print( math.log( 0.5 ) )
print( math.log( 0.4 ) )
print( math.log( 0.3 ) )
print( math.log( 0.2 ) )
print( math.log( 0.1 ) )
print( math.log( 0.05 ) )
print( math.log( 0.01 ) )

0.0
-0.05129329438755058
-0.10536051565782628
-0.2231435513142097
-0.35667494393873245
-0.5108256237659907
-0.6931471805599453
-0.916290731874155
-1.2039728043259361
-1.6094379124341003
-2.3025850929940455
-2.995732273553991
-4.605170185988091


In [5]:
import numpy as np 

b = 5.2 
print( np.log(b))


1.6486586255873816


In [6]:
import math

print( math.e ** 1.6486586255873816 )

5.199999999999999


In [7]:
softmax_outputs = np.array(
    [
        [0.7, 0.1, 0.2],
        [0.1, 0.5, 0.4],
        [0.02, 0.9, 0.08]
    ]
)

class_targets = [ 0, 1, 1 ]

In [8]:
for targ_idx, distribution in zip( class_targets, softmax_outputs):
    print( distribution[targ_idx] )

0.7
0.5
0.9


In [11]:
softmax_outputs = np.array(
    [
        [0.7, 0.1, 0.2],
        [0.1, 0.5, 0.4],
        [0.02, 0.9, 0.08]
    ]
)

class_targets = [ 0, 1, 1 ]

print( softmax_outputs[ [0, 1, 2 ], class_targets ] )

[0.7 0.5 0.9]


In [12]:
print(
    softmax_outputs[
        range(
            len(softmax_outputs)
        ), class_targets
    ]
)

[0.7 0.5 0.9]


In [13]:
print( -np.log( softmax_outputs[
    range(
        len(softmax_outputs)
    ), class_targets
] ) )

[0.35667494 0.69314718 0.10536052]


In [14]:
neg_log = -np.log( softmax_outputs[
    range(
        len(softmax_outputs)
    ), class_targets
] )

average_loss = np.mean( neg_log )
print( average_loss )

0.38506088005216804


In [15]:
import numpy as np 

softmax_outputs = np.array(
    [
        [0.7, 0.1, 0.2],
        [0.1, 0.5, 0.4],
        [0.02, 0.9, 0.08]
    ]
)

class_targets = np.array(
    [
        [1, 0, 0],
        [0, 1, 0],
        [0, 1, 0]
    ]
)

# Probabilities for taget values
# only if categorical labels
if len( class_targets.shape ) == 1:
    correct_confidences = softmax_outputs[
        range(
            len(softmax_outputs)
        ), class_targets
    ]
elif len( class_targets.shape ) == 2:
    correct_confidences = np.sum(
        softmax_outputs * class_targets,
        axis = 1
    )
    
neg_log = -np.log( correct_confidences )

average_loss = np.mean( neg_log )
print( average_loss )

0.38506088005216804


In [16]:
import numpy as np
-np.log( 0 )

/tmp/ipykernel_19691/1710585469.py:2: RuntimeWarning: divide by zero encountered in log
  -np.log( 0 )


inf

In [ ]:
# Common loss class
class Loss:
    
    # Calculates the data and regularization losses
    # given model output and ground truth values
    def calculate(self, output, y):
        
        # Calculate sample losses
        sample_losses = self.forward(output, y)
        
        # Calculate mean loss
        data_loss = np.mean(sample_losses)
        
        # Return loss
        return data_loss

In [ ]:
# Cross-entropy loss
class Loss_CategoricalCrossentropy( Loss ):
    
    # Forward pass
    def forward( self, y_pred, y_true ):
        
        # Number of samples in a batch
        samples = len( y_pred )
        
        # Clip data to prevent division by 0
        # Clip both sides to not drag mean towards any value
        y_pred_clipped = np.clip( y_pred, 1e-7, 1 - 1e-7 )
        
        # Probabilities for target values - 
        # only if categorical labels
        if len( y_true.shape ) == 1:
            correct_confidences = y_pred_clipped[
                range( samples ),
                y_true
            ]
        elif len( y_true.shape ) == 2:
            correct_confidences = np.sum(
                y_pred_clipped * y_true,
                axis = 1
            )
        
        # Losses
        negative_log_likelihoods = -np.log( correct_confidences )
        return negative_log_likelihoods