In [2]:
layer_outputs = [4.8, 1.21, 2.385]

E = 2.71828182846

exp_values = []

for output in layer_outputs:
    exp_values.append(E ** output)
    
print( 'exponentiated values: ' )
print(exp_values)

exponentiated values: 
[121.51041751893969, 3.3534846525504487, 10.85906266492961]


In [3]:
norm_base = sum( exp_values )
norm_values = []

for value in exp_values:
    norm_values.append( value / norm_base )
    
print( 'Normalized exponentiated values: ' )
print( norm_values )

print( 'Sum of normalized values: ', sum( norm_values ) )

Normalized exponentiated values: 
[0.8952826639573506, 0.024708306782070668, 0.08000902926057876]
Sum of normalized values:  1.0


In [5]:
# Ahora con numpy

import numpy as np

layer_outputs = [4.8, 1.21, 2.385]

exp_values = np.exp( layer_outputs )
print( 'exponentiated values: ' )
print(exp_values)

exponentiated values: 
[121.51041752   3.35348465  10.85906266]


In [6]:
norm_values = exp_values / np.sum( exp_values )
print( 'Normalized exponentiated values: ' )
print( norm_values )
print( 'Sum of normalized values: ', np.sum( norm_values ) )

Normalized exponentiated values: 
[0.89528266 0.02470831 0.08000903]
Sum of normalized values:  0.9999999999999999


In [7]:
import numpy as np

layer_outputs = np.array(
    [
        [4.8, 1.21, 2.385],
        [8.9, -1.81, 0.2],
        [1.41, 1.051, 0.026]
    ]
)

print( 'Sum without axis' )
print( np.sum( layer_outputs ) )

print( 'This will be identical to the above since default is None:' )
print( np.sum( layer_outputs, axis = None ) )

Sum without axis
18.172
This will be identical to the above since default is None:
18.172


In [9]:
print( 'Another way to think of it w/ a matrix == axis 0: columns: ' )
print( np.sum( layer_outputs, axis = 0 ) )

Another way to think of it w/ a matrix == axis 0: columns: 
[15.11   0.451  2.611]


In [10]:
print( 'But we want to sum the rows instead, like this w/ raw py: ' )

for i in layer_outputs:
    print( sum( i ) )

But we want to sum the rows instead, like this w/ raw py: 
8.395
7.29
2.4869999999999997
