In [9]:
import numpy as np

output_soft_attention = np.array([[1, 2, 3], [4, 5, 6]])
output_self_attention = np.array([[7, 8, 9], [10, 11, 12]])

weight_soft_attention = 0.3
weight_self_attention = 0.8

suma_ponderada = (weight_soft_attention * output_soft_attention) + (weight_self_attention * output_self_attention)

promedio_ponderado = (weight_soft_attention * output_soft_attention + weight_self_attention * output_self_attention) / (weight_soft_attention + weight_self_attention)

print( "Suma ponderada: ")
print(suma_ponderada)
print("")
print( "Promedio ponderado: ")
print(promedio_ponderado)

Suma ponderada: 
[[ 5.9  7.   8.1]
 [ 9.2 10.3 11.4]]

Promedio ponderado: 
[[ 5.36363636  6.36363636  7.36363636]
 [ 8.36363636  9.36363636 10.36363636]]
