In [5]:
import numpy as np

output_soft_attention = np.array(
  [
    [1, 2, 3],
    [4, 5, 6],
  ]
)

output_self_attention = np.array(
  [
    [7, 8, 9],
    [10, 11, 12],
  ]
)

concatenated = np.concatenate([output_soft_attention, output_self_attention], axis=-1)

print( "output_soft_attention: ")
print("")
print(output_soft_attention)
print("")
print( "output_self_attention: ")
print("")
print(output_self_attention)
print("")
print( "concatenated: ")
print("")
print(concatenated)

output_soft_attention: 

[[1 2 3]
 [4 5 6]]

output_self_attention: 

[[ 7  8  9]
 [10 11 12]]

concatenated: 

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
